id: I3C86AC57
legacy_id: P006627
ocr_import_info:
  bdrc_scan_id: W00EGS1016299
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T03:14:38'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T11:26:26.431346+00:00'
last_modified: 2022-08-30 19:38:14.506832
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00EGS1016299
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW00EGS1016299
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། དྲི་མེད་འོད་ཟེར། ༼སྡེ་དགེ་པར་མ།༽
  author: ཀློང་ཆེན་རབ་འབྱམས་པ་དྲི་མེད་འོད་ཟེར།
statistics:
  ocr_word_mean_confidence_index: 0.700513534810551
  ocr_word_median_confidence_index: 0.7699999809265137
quality: null
bases:
  I1CZ5004:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ5004
      total_pages: 1276
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1CZ5004.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.6839812427438112
    legacy_id: v004
  I1CZ5003:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ5003
      total_pages: 1136
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1CZ5003.txt
    statistics:
      ocr_word_median_confidence_index: 0.7699999809265137
      ocr_word_mean_confidence_index: 0.7000499059793198
    legacy_id: v003
  I1CZ5005:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ5005
      total_pages: 928
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1CZ5005.txt
    statistics:
      ocr_word_median_confidence_index: 0.6000000238418579
      ocr_word_mean_confidence_index: 0.5841686780296307
    legacy_id: v005
  I1CZ5002:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ5002
      total_pages: 1266
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1CZ5002.txt
    statistics:
      ocr_word_median_confidence_index: 0.8199999928474426
      ocr_word_mean_confidence_index: 0.7491180489074482
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
